name: Cypress Tests

on: [push]

jobs:
  ui-chrome-tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.19.0-chrome100-ff99-edge
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'UI Tests - Chrome'
        run: cypress open --config-file=cypress.config.ts
